port: 9333
host: 192.168.0.2
initial_peers:
#  - "95.154.71.53:9333"
    - "5.35.98.126:9333"
    - "yglamazdin.fvds.ru:9333"
    - "95.154.71.53:9333"
    - "api.robotsimulator.ru:9333"
    - "api.robotsimulator.ru:9334"
address: OutkXjncE8LxdGH5Gh8bwhr8VnpfYiZDgRL1URhW8FpN7sQ_SERV1
