port: 9335
host: 127.0.0.1
initial_peers:
    - "127.0.0.1:9333"
    - "5.35.98.126:9333"
    - "yglamazdin.fvds.ru:9333"
    - "95.154.71.53:9333"
    - "api.robotsimulator.ru:9333"
    - "api.robotsimulator.ru:9334"

address: OutGkzTP3mv8x7t3zwUM3Ly8YfhEY79oNdpBRgtobK2fDSFH_HOME3
