port: 9333
host: 5.35.98.126
is_miner: True
#pause_before_try_block: 20
miners_storage_size: 100

initial_peers:
    - "95.154.71.53:9333"
    - "95.154.71.53:9333"
address_reward: V1Pp6Hd4uUs8iwT7LWEEzFFUEiGfLwBXZUKuAP4a8MP78axPTVsK
