port: 9334
host: 5.35.98.126
is_miner: True
pause_before_try_block: 20
miners_storage_size: 10
miners_storage_height: 5
initial_peers:
#  - "95.154.71.53:9333"
    - "95.154.71.53:9333"
    - "95.154.71.53:9334"
    - "5.35.98.126:9333"
address_reward: AKMxvU7oJPWraHpaMxiYebN6eZn92DJNSqmQEGxzkB7m2b25okMh
