port: 9336
host: 127.0.0.1
is_miner: True
initial_peers:
    - "127.0.0.1:9333"
    - "127.0.0.1:9334"
    - "127.0.0.1:9335"
    - "5.35.98.126:9333"
    - "yglamazdin.fvds.ru:9333"
    - "95.154.71.53:9333"
    - "api.robotsimulator.ru:9333"
    - "api.robotsimulator.ru:9334"
address_reward: Runsb7FX8Qzr3SBxzWmBpNJD3sG2HCSxLHgbXEfiUTPiGLEfbQsZ
